/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regime/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Regime Latest
         * @description The most recent persisted regime snapshot (input charts + metrics + conclusion).
         */
        get: operations["regime_latest_api_regime_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regime/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regime Refresh
         * @description Start a fresh MarketRegimeWorkflow; returns the workflow id to poll.
         */
        post: operations["regime_refresh_api_regime_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regime/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Regime Status */
        get: operations["regime_status_api_regime_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bars
         * @description OHLCV for client-side candlestick rendering (most-recent `limit` bars).
         */
        get: operations["bars_api_bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis Latest */
        get: operations["analysis_latest_api_analysis__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analysis Refresh */
        post: operations["analysis_refresh_api_analysis_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/status/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis Status */
        get: operations["analysis_status_api_analysis_status__workflow_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Llm Usage */
        get: operations["llm_usage_api_llm_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jobs
         * @description Which trigger types are currently running (so the UI can disable buttons).
         */
        get: operations["jobs_api_screener_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_screener_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan
         * @description Rally-screen: shallow-screen the rallying sectors and drop the hits into a group. The
         *     group name is auto-generated when not given; the persist activity creates the group.
         */
        post: operations["scan_api_screener_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Groups */
        get: operations["groups_api_screener_groups_get"];
        put?: never;
        /** Create Group */
        post: operations["create_group_api_screener_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/groups/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Group */
        delete: operations["delete_group_api_screener_groups__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candidates */
        get: operations["candidates_api_screener_candidates_get"];
        put?: never;
        /**
         * Add Candidate
         * @description Manually add a ticker (into a group when given): validate + score it like a scan hit.
         */
        post: operations["add_candidate_api_screener_candidates_post"];
        /** Clear Candidates */
        delete: operations["clear_candidates_api_screener_candidates_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/ai-pick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ai Pick
         * @description AI pick: describe what you want; the LLM proposes liquid good-performers, each validated
         *     by a real data fetch + shallow-scored, dropped into a group. No-op without an LLM key.
         */
        post: operations["ai_pick_api_screener_ai_pick_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/candidates/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Candidate */
        delete: operations["delete_candidate_api_screener_candidates__symbol__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/alpha/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate */
        post: operations["evaluate_api_screener_alpha_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/alpha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alpha */
        get: operations["alpha_api_screener_alpha_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/alpha/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Alpha */
        delete: operations["delete_alpha_api_screener_alpha__symbol__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/alpha/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_screener_alpha_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/downgraded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Downgraded */
        get: operations["downgraded_api_screener_downgraded_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddRequest */
        AddRequest: {
            /** Symbol */
            symbol: string;
            /**
             * Group
             * @default
             */
            group: string;
        };
        /** AiPickRequest */
        AiPickRequest: {
            /** Query */
            query: string;
            /**
             * Group
             * @default
             */
            group: string;
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /**
         * AlphaItem
         * @description A live ALPHA list entry. The underlying TickerAnalysis is stored separately
         *     (`analyses` table) and powers the detail view via the existing Ticker components.
         */
        AlphaItem: {
            /** Symbol */
            symbol: string;
            verdict: components["schemas"]["AlphaVerdict"];
            /**
             * Analysis Generated At
             * Format: date-time
             */
            analysis_generated_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Levels */
            levels?: components["schemas"]["KeyLevel"][];
            /** Gaps */
            gaps?: components["schemas"]["GapNote"][];
        };
        /**
         * AlphaReason
         * @description One structured, reviewable reason behind an alpha verdict.
         */
        AlphaReason: {
            /** Category */
            category: string;
            /** Detail */
            detail: string;
            /** @default neutral */
            status: components["schemas"]["Bias"];
        };
        /**
         * AlphaVerdict
         * @description agent2/agent3 output: is this a genuine alpha opportunity, why, and what it saw.
         */
        AlphaVerdict: {
            /** Symbol */
            symbol: string;
            /**
             * Is Alpha
             * @default false
             */
            is_alpha: boolean;
            /**
             * Conviction
             * @default 0
             */
            conviction: number;
            /**
             * Stage
             * @default
             */
            stage: string;
            /**
             * Sector
             * @default
             */
            sector: string;
            /**
             * Regime Alignment
             * @default
             */
            regime_alignment: string;
            /** Entry */
            entry?: number | null;
            /** Stop */
            stop?: number | null;
            /** Target */
            target?: number | null;
            /** Rr */
            rr?: number | null;
            /** Reasons */
            reasons?: components["schemas"]["AlphaReason"][];
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Source
             * @default deterministic
             */
            source: string;
            /**
             * Inputs
             * @default
             */
            inputs: string;
            /**
             * Action State
             * @default
             */
            action_state: string;
        };
        /** AnalysisSummary */
        AnalysisSummary: {
            overall_bias: components["schemas"]["Bias"];
            /** Headline */
            headline: string;
            /** Price Now */
            price_now: number;
            /** Best Setup Id */
            best_setup_id?: string | null;
            /** Narrative */
            narrative?: string | null;
        };
        /** AnalyticalNote */
        AnalyticalNote: {
            /** Key */
            key: string;
            severity: components["schemas"]["NoteSeverity"];
            /** Message */
            message: string;
        };
        /**
         * Bias
         * @enum {string}
         */
        Bias: "bullish" | "neutral" | "bearish";
        /**
         * CandidateStatus
         * @enum {string}
         */
        CandidateStatus: "pending" | "evaluating" | "alpha" | "not_alpha";
        /** Candle */
        Candle: {
            /** Time */
            time: number;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
        };
        /** ChartArtifact */
        ChartArtifact: {
            timeframe: components["schemas"]["Timeframe"];
            /** Png Path */
            png_path: string;
            /** Pattern Ids */
            pattern_ids?: string[];
        };
        /** ChartMarker */
        ChartMarker: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Color
             * @default
             */
            color: string;
            /**
             * Position
             * @default belowBar
             */
            position: string;
            /**
             * Shape
             * @default circle
             */
            shape: string;
        };
        /** CreateGroupRequest */
        CreateGroupRequest: {
            /** Name */
            name: string;
        };
        /** DetectedPattern */
        DetectedPattern: {
            /** Id */
            id: string;
            /** Pattern Type */
            pattern_type: string;
            timeframe: components["schemas"]["Timeframe"];
            status: components["schemas"]["PatternStatus"];
            /** Geometry Confidence */
            geometry_confidence: number;
            /** Confidence */
            confidence: number;
            /** Pivots */
            pivots?: components["schemas"]["PivotPoint"][];
            /** Levels */
            levels?: {
                [key: string]: number;
            };
            /** Prior Resistance */
            prior_resistance?: number[];
            /** Volume */
            volume?: {
                [key: string]: number;
            };
            /**
             * Region Start
             * Format: date-time
             */
            region_start: string;
            /**
             * Region End
             * Format: date-time
             */
            region_end: string;
            /**
             * Region Start Idx
             * @default 0
             */
            region_start_idx: number;
            /**
             * Region End Idx
             * @default 0
             */
            region_end_idx: number;
            /** Entry */
            entry?: number | null;
            /** Stop */
            stop?: number | null;
            /** Target */
            target?: number | null;
            /** Rr Ratio */
            rr_ratio?: number | null;
            /**
             * Direction
             * @default bullish
             */
            direction: string;
            /**
             * Tier
             * @default core
             */
            tier: string;
            /** Parent Id */
            parent_id?: string | null;
            /** Child Ids */
            child_ids?: string[];
            /** Conflicts With */
            conflicts_with?: string[];
            /** Caution */
            caution?: string | null;
            /**
             * Role
             * @default considered
             */
            role: string;
            /** Cluster Id */
            cluster_id?: number | null;
            /** Label Override */
            label_override?: string | null;
            /** Chart Png */
            chart_png?: string | null;
            /** Llm Is Valid */
            llm_is_valid?: boolean | null;
            /** Llm Label */
            llm_label?: string | null;
            /** Llm Rationale */
            llm_rationale?: string | null;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /**
         * DowngradedItem
         * @description A formerly-alpha name that no longer qualifies.
         */
        DowngradedItem: {
            /** Symbol */
            symbol: string;
            /**
             * Prior Conviction
             * @default 0
             */
            prior_conviction: number;
            /**
             * Prior Summary
             * @default
             */
            prior_summary: string;
            /**
             * Downgrade Reason
             * @default
             */
            downgrade_reason: string;
            /**
             * Downgraded At
             * Format: date-time
             */
            downgraded_at: string;
        };
        /**
         * GapNote
         * @description A textbook (non-common) price gap worth the trader's attention. Common gaps are
         *     suppressed (they add nothing).
         */
        GapNote: {
            /** Date */
            date: string;
            /** Kind */
            kind: string;
            /** Direction */
            direction: string;
            /** Gap Pct */
            gap_pct: number;
            /** Lower */
            lower: number;
            /** Upper */
            upper: number;
            /**
             * Filled
             * @default false
             */
            filled: boolean;
            /** Volume Ratio */
            volume_ratio?: number | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndicatorSnapshot */
        IndicatorSnapshot: {
            timeframe: components["schemas"]["Timeframe"];
            /** Close */
            close: number;
            /** Sma50 */
            sma50?: number | null;
            /** Sma150 */
            sma150?: number | null;
            /** Sma200 */
            sma200?: number | null;
            /** Ema21 */
            ema21?: number | null;
            /** Rsi14 */
            rsi14?: number | null;
            /** Atr Pct */
            atr_pct?: number | null;
            /** Realized Vol */
            realized_vol?: number | null;
            /** Rel Volume */
            rel_volume?: number | null;
            /** Avg Dollar Volume 20 */
            avg_dollar_volume_20?: number | null;
            /** High 52W */
            high_52w?: number | null;
            /** Low 52W */
            low_52w?: number | null;
            /** Pct From 52W High */
            pct_from_52w_high?: number | null;
            /** Pct Above Sma50 */
            pct_above_sma50?: number | null;
            /** Trend Template Pass */
            trend_template_pass?: boolean | null;
        };
        /**
         * KeyLevel
         * @description A price point worth watching on an alpha name (resistance / support / a high).
         */
        KeyLevel: {
            /** Price */
            price: number;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /**
             * Distance Pct
             * @default 0
             */
            distance_pct: number;
        };
        /**
         * LongPosture
         * @description How historically hospitable the regime has been to new long swing exposure.
         *
         *     A characterisation of market conditions, not a recommended course of action.
         * @enum {string}
         */
        LongPosture: "aggressive" | "selective" | "defensive" | "cash";
        /**
         * NoteSeverity
         * @enum {string}
         */
        NoteSeverity: "info" | "caution" | "warning";
        /**
         * PatternStatus
         * @enum {string}
         */
        PatternStatus: "forming" | "confirmed" | "triggered" | "invalidated";
        /** PivotPoint */
        PivotPoint: {
            /** Idx */
            idx: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Price */
            price: number;
            /** Kind */
            kind: string;
            /**
             * Provisional
             * @default false
             */
            provisional: boolean;
        };
        /** PriceNote */
        PriceNote: {
            /** Price */
            price: number;
            /** Label */
            label: string;
            /** Kind */
            kind: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Symbol */
            symbol: string;
        };
        /** RegimeCandle */
        RegimeCandle: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
        };
        /**
         * RegimeChart
         * @description The actual time-series behind a consideration, so the dashboard can draw it.
         */
        RegimeChart: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /**
             * Pillar Key
             * @default
             */
            pillar_key: string;
            /** Series */
            series?: components["schemas"]["RegimeSeries"][];
            /** Markers */
            markers?: components["schemas"]["ChartMarker"][];
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * RegimeMetric
         * @description One book-grounded reading (e.g. distribution-day count, Power Trend on/off).
         */
        RegimeMetric: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** @default neutral */
            status: components["schemas"]["Bias"];
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Source Tag
             * @default
             */
            source_tag: string;
            /** Numeric */
            numeric?: number | null;
            /**
             * Flag
             * @default
             */
            flag: string;
        };
        /**
         * RegimePillar
         * @description A cluster of related metrics with an aggregate status (one of the 5 pillars).
         */
        RegimePillar: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** @default neutral */
            status: components["schemas"]["Bias"];
            /**
             * Score
             * @default 0
             */
            score: number;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Metrics */
            metrics?: components["schemas"]["RegimeMetric"][];
        };
        /** RegimePoint */
        RegimePoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Value */
            value: number;
        };
        /** RegimeSeries */
        RegimeSeries: {
            /** Label */
            label: string;
            /**
             * Kind
             * @default line
             */
            kind: string;
            /**
             * Color
             * @default
             */
            color: string;
            /** Points */
            points?: components["schemas"]["RegimePoint"][];
            /** Candles */
            candles?: components["schemas"]["RegimeCandle"][];
        };
        /**
         * RegimeSnapshot
         * @description The full market-conditions read: the input data (charts + metrics) AND the
         *     conclusion (mood/state/posture/narrative). Persisted whole so the dashboard
         *     redraws entirely from the DB with no re-fetch.
         */
        RegimeSnapshot: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** @default neutral */
            overall_state: components["schemas"]["RegimeState"];
            /** @default selective */
            long_posture: components["schemas"]["LongPosture"];
            /**
             * Mood
             * @default
             */
            mood: string;
            /**
             * Score
             * @default 0
             */
            score: number;
            /**
             * Headline
             * @default
             */
            headline: string;
            /**
             * Narrative
             * @default
             */
            narrative: string;
            /**
             * Source
             * @default deterministic
             */
            source: string;
            /** Pillars */
            pillars?: components["schemas"]["RegimePillar"][];
            /** Charts */
            charts?: components["schemas"]["RegimeChart"][];
        };
        /**
         * RegimeState
         * @description Overall market state — the IBD/Weinstein-style ladder for a LONG book.
         * @enum {string}
         */
        RegimeState: "confirmed_uptrend" | "uptrend_under_pressure" | "neutral" | "correction" | "bear";
        /**
         * ScreenFactor
         * @description One pre-screen reading shown on a scanner candidate row.
         */
        ScreenFactor: {
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** @default neutral */
            status: components["schemas"]["Bias"];
        };
        /**
         * ScreenerCandidate
         * @description A scanner hit — a ticker that MIGHT have a good trade (cheap pre-screen, not yet
         *     the full agent analysis). The user selects these to push into the alpha pipeline.
         *     Once evaluated, it carries the agent's verdict (reasons + the inputs it saw).
         */
        ScreenerCandidate: {
            /** Symbol */
            symbol: string;
            /** Sector */
            sector: string;
            /**
             * Score
             * @default 0
             */
            score: number;
            /** @default pending */
            status: components["schemas"]["CandidateStatus"];
            /** Factors */
            factors?: components["schemas"]["ScreenFactor"][];
            /**
             * Source
             * @default screen
             */
            source: string;
            /**
             * Group
             * @default
             */
            group: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            verdict?: components["schemas"]["AlphaVerdict"] | null;
        };
        /**
         * ScreenerGroup
         * @description A named scanner group (a bucket of candidates). kind: custom | scan | ai.
         */
        ScreenerGroup: {
            /** Name */
            name: string;
            /**
             * Kind
             * @default custom
             */
            kind: string;
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /** Shape */
        Shape: {
            kind: components["schemas"]["ShapeKind"];
            /** Points */
            points?: components["schemas"]["ShapePoint"][];
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Role
             * @default primary
             */
            role: string;
            /** Color */
            color?: string | null;
            /** Touch Count */
            touch_count?: number | null;
            /** Fit Residual */
            fit_residual?: number | null;
        };
        /**
         * ShapeKind
         * @enum {string}
         */
        ShapeKind: "trendline" | "curve" | "hline" | "zone" | "marker";
        /** ShapePoint */
        ShapePoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Price */
            price: number;
        };
        /** SymbolsRequest */
        SymbolsRequest: {
            /**
             * Symbols
             * @default []
             */
            symbols: string[];
        };
        /**
         * SynthesisRead
         * @description The cross-timeframe fusion — the big-picture call over all the per-TF theses.
         */
        SynthesisRead: {
            /** @default neutral */
            overall_bias: components["schemas"]["Bias"];
            /**
             * Headline
             * @default
             */
            headline: string;
            primary_timeframe?: components["schemas"]["Timeframe"] | null;
            /**
             * Nested Context
             * @default
             */
            nested_context: string;
            /**
             * Long Term Forming
             * @default
             */
            long_term_forming: string;
        };
        /** TickerAnalysis */
        TickerAnalysis: {
            /**
             * Schema Version
             * @default 3
             */
            schema_version: number;
            /** Symbol */
            symbol: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Timeframes */
            timeframes?: components["schemas"]["Timeframe"][];
            summary: components["schemas"]["AnalysisSummary"];
            /** Patterns */
            patterns?: components["schemas"]["DetectedPattern"][];
            /** Charts */
            charts?: components["schemas"]["ChartArtifact"][];
            /** Notes */
            notes?: components["schemas"]["AnalyticalNote"][];
            /** Indicators */
            indicators?: components["schemas"]["IndicatorSnapshot"][];
            /** Theses */
            theses?: components["schemas"]["TimeframeThesis"][];
            synthesis?: components["schemas"]["SynthesisRead"] | null;
        };
        /**
         * Timeframe
         * @enum {string}
         */
        Timeframe: "daily" | "weekly" | "monthly";
        /**
         * TimeframeThesis
         * @description What the AI analyst concluded for ONE timeframe — its own pattern call, the exact
         *     levels (verified via the geometry tools), the shapes to draw, and an audit trail.
         */
        TimeframeThesis: {
            timeframe: components["schemas"]["Timeframe"];
            /** Pattern Label */
            pattern_label: string;
            /** @default forming */
            status: components["schemas"]["PatternStatus"];
            /**
             * Direction
             * @default bullish
             */
            direction: string;
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
            /** Entry */
            entry?: number | null;
            /** Breakout */
            breakout?: number | null;
            /** Target */
            target?: number | null;
            /** Target2 */
            target2?: number | null;
            /** Stop */
            stop?: number | null;
            /** Rr Ratio */
            rr_ratio?: number | null;
            /**
             * Action State
             * @default
             */
            action_state: string;
            /** Trigger Zone Low */
            trigger_zone_low?: number | null;
            /** Trigger Zone High */
            trigger_zone_high?: number | null;
            /** Shapes */
            shapes?: components["schemas"]["Shape"][];
            /** Price Notes */
            price_notes?: components["schemas"]["PriceNote"][];
            /** Supporting Factors */
            supporting_factors?: string[];
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** Transcript */
            transcript?: string[];
            /**
             * Source
             * @default llm
             */
            source: string;
            /** Seed Pattern Ids */
            seed_pattern_ids?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    regime_latest_api_regime_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimeSnapshot"] | null;
                };
            };
        };
    };
    regime_refresh_api_regime_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    regime_status_api_regime_status_get: {
        parameters: {
            query: {
                workflow_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bars_api_bars_get: {
        parameters: {
            query: {
                symbol: string;
                timeframe?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candle"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analysis_latest_api_analysis__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerAnalysis"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analysis_refresh_api_analysis_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analysis_status_api_analysis_status__workflow_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_usage_api_llm_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    jobs_api_screener_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    status_api_screener_status_get: {
        parameters: {
            query: {
                workflow_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_api_screener_scan_post: {
        parameters: {
            query?: {
                group?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    groups_api_screener_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerGroup"][];
                };
            };
        };
    };
    create_group_api_screener_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerGroup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_group_api_screener_groups__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidates_api_screener_candidates_get: {
        parameters: {
            query?: {
                group?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerCandidate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_candidate_api_screener_candidates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_candidates_api_screener_candidates_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    ai_pick_api_screener_ai_pick_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiPickRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_candidate_api_screener_candidates__symbol__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_api_screener_alpha_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SymbolsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alpha_api_screener_alpha_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlphaItem"][];
                };
            };
        };
    };
    delete_alpha_api_screener_alpha__symbol__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_screener_alpha_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SymbolsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    downgraded_api_screener_downgraded_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DowngradedItem"][];
                };
            };
        };
    };
}
